/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AllRouteImport } from './routes/all'
import { Route as SuggestRouteImport } from './routes/suggest'
import { Route as ItinerariesSlugRouteImport } from './routes/itineraries.$slug'
import { Route as RecommendationsSlugRouteImport } from './routes/recommendations.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AllRoute = AllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestRoute = SuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesSlugRoute = ItinerariesSlugRouteImport.update({
  id: '/itineraries/$slug',
  path: '/itineraries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsSlugRoute = RecommendationsSlugRouteImport.update({
  id: '/recommendations/$slug',
  path: '/recommendations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/all': typeof AllRoute
  '/suggest': typeof SuggestRoute
  '/itineraries/$slug': typeof ItinerariesSlugRoute
  '/recommendations/$slug': typeof RecommendationsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/all': typeof AllRoute
  '/suggest': typeof SuggestRoute
  '/itineraries/$slug': typeof ItinerariesSlugRoute
  '/recommendations/$slug': typeof RecommendationsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/all': typeof AllRoute
  '/suggest': typeof SuggestRoute
  '/itineraries/$slug': typeof ItinerariesSlugRoute
  '/recommendations/$slug': typeof RecommendationsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/all'
    | '/suggest'
    | '/itineraries/$slug'
    | '/recommendations/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/all'
    | '/suggest'
    | '/itineraries/$slug'
    | '/recommendations/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/all'
    | '/suggest'
    | '/itineraries/$slug'
    | '/recommendations/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AllRoute: typeof AllRoute
  SuggestRoute: typeof SuggestRoute
  ItinerariesSlugRoute: typeof ItinerariesSlugRoute
  RecommendationsSlugRoute: typeof RecommendationsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all': {
      id: '/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggest': {
      id: '/suggest'
      path: '/suggest'
      fullPath: '/suggest'
      preLoaderRoute: typeof SuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/$slug': {
      id: '/itineraries/$slug'
      path: '/itineraries/$slug'
      fullPath: '/itineraries/$slug'
      preLoaderRoute: typeof ItinerariesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations/$slug': {
      id: '/recommendations/$slug'
      path: '/recommendations/$slug'
      fullPath: '/recommendations/$slug'
      preLoaderRoute: typeof RecommendationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AllRoute: AllRoute,
  SuggestRoute: SuggestRoute,
  ItinerariesSlugRoute: ItinerariesSlugRoute,
  RecommendationsSlugRoute: RecommendationsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
